### ISSUE TITLE
Silent failure on FASTQ files with empty sequence entries (i.e. empty lines)

### ISSUE THREAD

**Issue by roland-ewald** [arq5x/grabix#33]
There seems to be an assumption that the number in the second line of a `*.gbi` index file should be divisible by four. For example, this is checked in "bcbio": https://github.com/chapmanb/bcbio-nextgen/blob/0db025298367c133e8fad462646acd6a774c42ad/bcbio/ngsalign/alignprep.py#L274

Is this assumption (still) valid? I'm asking because I am running into problems when using the grabix master branch with the latest development version of bcbio. However, grabix 0.1.6 seems to work fine (I tried to pinpoint the issue to [one of the changes between 0.1.6 and 0.1.7](https://github.com/arq5x/grabix/compare/0.1.6...v0.1.7), but was not successful so far. The sample fastq data as generated in `test.sh` also seems to work well, but it does fail on other (larger) fastq files. Any ideas?

**Comment by brentp** [comment]
can you share a test-case that demonstrates the bug? I assume the check in bcbio is simply because it's a fastq.

**Comment by roland-ewald** [comment]
Yes, I will try to make this fail with a much smaller fastq file that I can share.

**Comment by roland-ewald** [comment]
I could not really reproduce it with any public fastq file (yet), but it seems to be happening for very large files (fq.gz > 2GB), so could it be some kind of overflow issue? I am using the latest htslib release (1.6.0) on Ubuntu 16.04 LTS. I will try this systematically with larger NA12878 fastq files tomorrow.

**Comment by roland-ewald** [comment]
I could now narrow down the problem further. The problem appears when the FASTQ sequence (and consequently, the quality string) are empty (which is [kind of(?) supported by the spec](http://maq.sourceforge.net/fastq.shtml)), e.g. like so:

````
@SRR1517848.3 3/1

+

````
To reproduce this, please find the first 128 sequences from the public [`SRR1517848`](http://www.internationalgenome.org/data-portal/search?q=SRR1517848) sample attached, both normal and with the third entry being empty. In the latter case, `grabix` fails silently (return code is `0`) and stops, i.e. it writes `10` instead of `128` as file length into the `*.gbi` file (this is also in the tarball).

I think `grabix` should either fail non-silently here, or it should continue reading the FASTQ file. Let me know if you would like me to prepare a patch or an automated new test to `test.sh`.

Sample files: [grabix-33.tar.gz](https://github.com/arq5x/grabix/files/1392027/grabix-33.tar.gz)

**Comment by brentp** [comment]
I have just pushed a fix for this. Thanks for reporting.

**Comment by roland-ewald** [comment]
Great, thank you for the quick fix!

**Comment by chapmanb** [comment]
Thanks much for the quick fix. I pushed a bioconda package so this is now available if you run a bcbio tools update. Thanks again.
