### ISSUE TITLE
Won't Compile !!! 

### ISSUE THREAD

**Issue by SeAL80s** [arq5x/grabix#38]
Can you provide the Binary file grabix or add a document . What compiler do you use ? what system do you support ? Windows ? Linux ? I cann't read c++ code . In my system it output error : 
grabix.cpp : In fundtion 'int create_grabix_index(std::__cxx11::string) '
error:invalid conversion from 'char' to 'char*' [-fpermissive] 
line ->s = '\0' 
Can you simply provide the compiled grabix ? 
Tks

**Comment by brentp** [comment]
you can get a compiled version of grabix from [bioconda](https://bioconda.github.io/recipes/grabix/README.html)

Is the output you show above from using `make`? can you show the full command, and output and your version of g++?

**Comment by slw287r** [comment]
change all three lines of

```
line ->s = '\0';
```

to 

```
line ->s = 0;
```

compiles well.

**Comment by arq5x** [comment]
Is this the new standard for a NULL terminator?

**Comment by jmarshall** [comment]
`'\0'` is as ever the NUL terminator character. But `line` is a _kstring_t_ so `line->s` is a pointer and it really wants `NULL`. Or `nullptr` if your C++ were [super-modern](https://en.wikipedia.org/wiki/C%2B%2B11#Null_pointer_constant) :smile:

**Comment by arq5x** [comment]
Gee, I was taught to always terminate a string with '\0'!  Thanks for the help!

**Comment by brentp** [comment]
this has been fixed by @smoe
