### ISSUE TITLE
Unclear license of grabix.cpp

### ISSUE THREAD

**Issue by smoe** [arq5x/grabix#5]
Please add a COPYRIGHT file and/or add a header for the license of grabix.cpp as in the other source files. I was about to finish Debian packaging of grabix when I found this info missing.

Cheers,

Steffen

**Comment by kyleabeauchamp** [comment]
+1 I think this is important for conda packaging as well.

**Comment by kyleabeauchamp** [comment]
Thanks for the fast response!
